FROM python:3.8-slim-buster
ADD requirements.txt /microservice/requirements.txt
RUN pip install -r /microservice/requirements.txt
ADD . /microservice
WORKDIR /microservice
ENTRYPOINT ["python"]
CMD ["app.py"]