FROM python:3.8-slim-buster
ADD Backend/requirements.txt /microservice/requirements.txt
RUN pip install -r /microservice/requirements.txt
ADD Backend /microservice
WORKDIR /microservice
ENTRYPOINT ["python"]
CMD ["app.py"]



#in compose version of docker file we have removed 
#ADD Backend/requirements.txt /microservice/requirements.txt
#ADD Backend /microservice

#because of 
#backend:
#    build:
#      context: Backend

#     so its already searching in the Backend directory
# same goes for frontend as well
#ENV Backend_URL=http://0.0.0.0:6000
