version: "3.6"

services:

  backend:
    build: Backend
    hostname: backend-host-payal
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - my-network

  frontend:
    build: Frontend
    hostname: frontend-host-payal
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend-host-payaldocker:8000/api
    ports:
      - "3000:3000"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network: {}